"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package(
        "scitex-notebook",
        skip_rules=(
            # 5/9 Python APIs unmapped to MCP tools (get_code_cells,
            # get_notebook_name, load_ipython_extension etc.) — IPython-
            # specific entry points that may stay Python-only by design.
            # Real architectural-parity gap; per-API decision needed.
            "§6",
        ),
    )
